t<-rep(0,21)
s<-rep(NA,30)

# Below are the residue sequences, taken from the Protein Data Bank
# The 30 proteins considered are from the following PDB entries:
# 2FBD, 1B5V, 132L, 1GD6, 3AB6
# 1VRK, 1PRW, 1DEG, 1CLM, 1CFD
# 1ZMR, 1V6S, 3PGK, 1QPG, 1LTK
# 5GMM, 4WUQ, 2NMX, 1HCB, 1CRM
# 102M, 2NRL, 1MYG, 1LHT, 1YMA
# 3IA3, 1W09, 1Z8U, 1W0B, 1W0A

s[1]<-"XADFDAVLKCWGPVEADYTTIGGLVLTRLFKEHPETQKLFPKFAGIAQADIAGNAAVSAHGATVLKKLGELLKAKGSHAAILKPLANSHATKHKIPINNFKLISEVLVKVMQEKAGLDAGGQTALRNVMGIIIADLEANYKELGFSG"
s[2]<-"MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKAGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG"
s[3]<-"GLSDGEWQLVLNVWGKVEADVAGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGNTVLTALGGILKKKGHHEAELTPLAQSHATKHKIPVKYLEFISEAIIQVLQSKHPGDFGADAQGAMSKALELFRNDMAAKYKELGFQG"
s[4]<-"GLSDDEWNHVLGIWAKVEPDLSAHGQEVIIRLFQLHPETQERFAKFKNLTTIDALKSSEEVKKHGTTVLTALGRILKQKNNHEQELKPLAESHATKHKIPVKYLEFICEIIVKVIAEKHPSDFGADSQAAMKKALELFRNDMASKYKEFGFQG"
s[5]<-"GLSDGEWQQVLNVWGKVEADIAGHGQEVLIRLFTGHPETLEKFDKFKHLKTEAEMKASEDLKKYGTVVLTALGGILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISDAIIHVLHSKHPGDFGADAQGAMTKALELFRNDIAAKYKELGFQG"

s[6]<-"MALLKANKDLISAGLKEFSVLLNQQVFNDPLVSEEDMVTVVEDWMNFYINYYRQQVTGEPQERDKALQELRQELNTLANPFLAKYRDFLKS"
s[7]<-"LLKANKDLISAGLKEFSVLLNQQVFNDPLVSEEDMVTVVEDWMNFYINYYRQQVTGEPQERDKALQELRQELNTLANPFLAKYRDFLKSHEL"
s[8]<-"MALLKANKDLISAGLKEFSVLLNQQVFNDALVSEEDMVTVVEDWMNFYINYYRQQVTGEPQERDKALQELRQELNTLANPFLAKYRDFLKSHELPSHPPPSS"
s[9]<-"SALLKANKDLISAGLKEFSVLLNQQVFNDALVSEEDMVTVVEDWMNFYINYYRQQVTGEPQERDKALQELRQELNTLANPFLAKYRDFLKSHELPSHPPPSS"
s[10]<-"LLKANKDLISAGLKEFSVLLNQQVFNDPLVSEEDMVTVVEDWMNFYINYYRQQVTGEPQERDKALQELRQELNTLANPFLAKYRDFLKSHEL"

s[11]<-"MASPDWGYDDKNGPEQWSKLYPIANGNNQSPVDIKTSETKHDTSLKPISVSYNPATAKEIINVGHSFHVNFEDNDNRSVLKGGPFSDSYRLFQFHFHWGSTNEHGSEHTVDGVKYSAELHVAHWNSAKYSSLAEAASKADGLAVIGVLMKVGEANPKLQKVLDALQAIKTKGKRAPFTNFDPSTLLPSSLDFWTYPGSLTHPPLYESVTWIICKESISVSSEQLAQFRSLLSNVEGDNAVPMQHNNRPTQPLKGRTVRASF"
s[12]<-"MSPDWGYDDKNGPEQWSKLYPIANGNNQSPVDIKTSETKHDTSLKPISVSYNPATAKEIINVGHSFHVNFEDNDNRSVLKGGPFSDSYRLFQFHFHWGSTNEHGSEHTVDGVKYSAELHVAHWNSAKYSSLAEAASKADGLAVIGVLMKVGEANPKLQKVLDALQAIKTKGKRAPFTNFDPSTLLPSSLDFWTYPGSLTHPPLYESVTWIICKESISVSSEQLAQFRSLLSNVEGDNAVPMQHNNRPTQPLKGRTVRASF"
s[13]<-"ASPDWGYDDKNGPEQWSKLYPIANGNNQSPVDIKTSETKHDTSLKPISVSYNPATAKEIINVGHSFHVNFEDNDNRSVLKGGPFSDSYRLFQFHFHWGSTNEHGSEHTVDGVKYSAELHVAHWNSAKYSSLAEAASKADGLAVIGVLMKVGEANPKLQKVLDALQAIKTKGKRAPFTNFDPSTLLPSSLDFWTYPGSLTHPPLYESVTWIICKESISVSSEQLAQFRSLLSNVEGDNAVPMQHNNRPTQPLKGRTVRASF"
s[14]<-"ASPDWGYDDKNGPEQWSKLYPIANGNNQSPVDIKTSETKHDTSLKPISVSYNPATAKEIINVGHSFHVNFEDNDNRSVLKGGPFSDSYRLFQFHFHWGSTNEHGSEHTVDGVKYSAELHVAHWNSAKYSSLAEAASKADGLAVIGVLMKVGEANPKLQKVLDALQAIKTKGKRAPFTNFDPSTLLPSSLDFWTYPGSLTHPPLYESVTWIICKESISVSSEQLAQFRSLLSNVEGDNAVPMQHNNRPTQPLKGRTVRASF"
s[15]<-"ASPDWGYDDKNGPEQWSKLYPIANGNNQSPVDIKTSETKHDTSLKPISVSYNPATAKEIINVGHSFHVNFEDNQDRSVLKGGPFSDSYRLFQFHFHWGSTNEHGSEHTVDGVKYSAELHVAHWNSAKYSSLAEAASKADGLAVIGVLMKVGEANPKLQKVLDALQAIKTKGKRAPFTNFDPSTLLPSSLDFWTYPGSLTHPPLYESVTWIICKESISVSSEQLAQFRSLLSNVEGDNAVPMQHNNRPTQPLKGRTVRASF"

s[16]<-"MSVIKMTDLDLAGKRVFIRADLNVPVKDGKVTSDARIRASLPTIELALKQGAKVMVTSHLGRPTEGEYNEEFSLLPVVNYLKDKLSNPVRLVKDYLDGVDVAEGELVVLENVRFNKGEKKDDETLSKKYAALCDVFVMDAFGTAHRAQASTHGIGKFADVACAGPLLAAELDALGKALKEPARPMVAIVGGSKVSTKLTVLDSLSKIADQLIVGGGIANTFIAAQGHDVGKSLYEADLVDEAKRLLTTCNIPVPSDVRVATEFSETAPATLKSVNDVKADEQILDIGDASAQELAEILKNAKTILWNGPVGVFEFPNFRKGTEIVANAIADSEAFSIAGGGDTLAAIDLFGIADKISYISTGGGAFLEFVEGKVLPAVAMLEERAKK"
s[17]<-"MRTLLDLDPKGKRVLVRVDYNVPVQDGKVQDETRILESLPTLRHLLAGGASLVLLSHLGRPKGPDPKYSLAPVGEALRAHLPEARFAPFPPGSEEARREAEALRPGEVLLLENVRFEPGEEKNDPELSARYARLGEAFVLDAFGSAHRAHASVVGVARLLPAYAGFLMEKEVRALSRLLKDPERPYAVVLGGAKVSDKIGVIESLLPRIDRLLIGGAMAFTFLKALGGEVGRSLVEEDRLDLAKDLLGRAEALGVRVYLPEDVVAAERIEAGVETRVFPARAIPVPYMGLDIGPKTREAFARALEGARTVFWNGPMGVFEVPPFDEGTLAVGQAIAALEGAFTVVGGGDSVAAVNRLGLKERFGHVSTGGGASLEFLEKGTLPGLEVLEG"
s[18]<-"XSLSSKLSVQDLDLKDKRVFIRVDFNVPLDGKKITSNQRIVAALPTIKYVLEHHPRYVVLASHLGRPNGERNEKYSLAPVAKELQSLLGKDVTFLNDCVGPEVEAAVKASAPGSVILLENLRYHIEEEGSRKVDGQKVKASKEDVQKFRHELSSLADVYINDAFGTAHRAHSSMVGFDLPQRAAGFLLEKELKYFGKALENPTRPFLAILGGAKVADKIQLIDNLLDKVDSIIIGGGMAFTFKKVLENTEIGDSIFDKAVGPEIAKLMEKAKAKGVEVVLPVDFIIADAFSASANTKTVTDKEGIPAGWQGLDNGPESRKLFAATVAKATVILWNGPPGVFEFEKFAAGTKALLDEVVKSSAAGNTVIIGGGDTATVAKKYGVTDKISHVSTGGGASLELLEGKELPGVAFLSEKK"
s[19]<-"SLSSKLSVQDLDLKDKRVFIRVDFNVPLDGKKITSNQRIVAALPTIKYVLEHHPRYVVLASHLGQPNGERNEKYSLAPVAKELQSLLGKDVTFLNDCVGPEVEAAVKASAPGSVILLENLRYHIEEEGSRKVDGQKVKASKEDVQKFRHELSSLADVYINDAFGTAHRAHSSMVGFDLPQRAAGFLLEKELKYFGKALENPTRPFLAILGGAKVADKIQLIDNLLDKVDSIIIGGGMAFTFKKVLENTEIGDSIFDKAGAEIVPKLMEKAKAKGVEVVLPVDFIIADAFSADANTKTVTDKEGIPAGWQGLDNGPESRKLFAATVAKAKTIVWNGPPGVFEFEKFAAGTKALLDEVVKSSAAGNTVIIGGGDTATVAKKYGVTDKISHVSTGGGASLELLEGKELPGVAFLSEKK"
s[20]<-"GHSMHHHHHHLGNKLSISDLKDIKNKKVLVRVDFNVPIENGIIKDTNRITATLPTINHLKKEGASKIILISHCGRPDGLRNEKYTLKPVAETLKGLLGEEVLFLNDCVGKEVEDKINAAKENSVILLENLRFHIEEEGKGVDANGNKVKANKEDVEKFQNDLTKLADVFINDAFGTAHRAHSSMVGVKLNVKASGFLMKKELEYFSKALENPQRPLLAILGGAKVSDKIQLIKNLLDKVDRMIIGGGMAYTFKKVLNNMKIGTSLFDEAGSKIVGEIMEKAKAKNVQIFLPVDFKIADNFDNNANTKFVTDEEGIPDNWMGLDAGPKSIENYKDVILTSKTVIWNGPQGVFEMPNFAKGSIECLNLVVEVTKKGAITIVGGGDTASLVEQQNKKNEISHVSTGGGASLELLEGKELPGVLALSNK"

s[21]<-"ADQLTDEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLNLMARKMKDTDSEEKLKEAFRVFDKDGNGFISAAELRHVMTNLGEKLTDEEVDEMIREADVDGDGQVNYEEFVQVMMAK"
s[22]<-"XADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYEEFVQMMTAK"
s[23]<-"TEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREANIDGDGQVNYEEFVQMMTA"
s[24]<-"AQELTEEQIAEFKEAFALFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLSLMARKMKEQDSEEELIEAFKVFDRDGNGLISAAELRHVMTNLGEKLTDDEVDEMIREADIDGDGHINYEEFVRMMVSK"
s[25]<-"ADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYEEFVQMMTAK"

s[26]<-"KTFTRCSLAREMYALGVPKSELPQWTCIAEHESSYRTNVVGPTNSNGSNDYGIFQINNYYWCQPSNGRFSYNECHLSCDALLTDNISNSVTCARKIKSQQGWTAWSTWKYCSGSLPSINDCF"
s[27]<-"KVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGYNTRATNYNAGDRATDYGIFQINSRYWCNDGKTPGAVNACHLSCSALLQDNIADAVACAKRVVRDPQGIRAWVAWRNRCQNRDVRQYVQGCGV"
s[28]<-"KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL"
s[29]<-"KTFTRCGLVHELRKHGFEENLMRNWVCLVEHESSRDTSKTNTNRNGSKDYGLFQINDRYWCSKGASPGKDCNVKCSDLLTDDITKAAKCAKKIYKRHRFDAWYGWKNHCQGSLPDISSC"
s[30]<-"FAGGTVSQRCLSCICKMESGCRNVGCKMDMGSLSCGYFQIKEAYWIDCGRPGSSWKSCAASSYCASLCVQNYMKRYAKWAGCPLRCEGFAREHNGGPRGCKKGSTIGYWNRLQKISGCHGVQ"
for (j in 1:30){
for (i in 1:nchar(s[j])){
  if (substr(s[j],i,i)=="A") t[1]<-t[1]+10/nchar(s[j])
  if (substr(s[j],i,i)=="C") t[2]<-t[2]+10/nchar(s[j])
  if (substr(s[j],i,i)=="D") t[3]<-t[3]+10/nchar(s[j])
  if (substr(s[j],i,i)=="E") t[4]<-t[4]+10/nchar(s[j])
  if (substr(s[j],i,i)=="F") t[5]<-t[5]+10/nchar(s[j])
  if (substr(s[j],i,i)=="G") t[6]<-t[6]+10/nchar(s[j])
  if (substr(s[j],i,i)=="H") t[7]<-t[7]+10/nchar(s[j])
  if (substr(s[j],i,i)=="I") t[8]<-t[8]+10/nchar(s[j])
  if (substr(s[j],i,i)=="K") t[9]<-t[9]+10/nchar(s[j])
  if (substr(s[j],i,i)=="L") t[10]<-t[10]+10/nchar(s[j])
  if (substr(s[j],i,i)=="M") t[11]<-t[11]+10/nchar(s[j])
  if (substr(s[j],i,i)=="N") t[12]<-t[12]+10/nchar(s[j])
  if (substr(s[j],i,i)=="P") t[13]<-t[13]+10/nchar(s[j])
  if (substr(s[j],i,i)=="Q") t[14]<-t[14]+10/nchar(s[j])
  if (substr(s[j],i,i)=="R") t[15]<-t[15]+10/nchar(s[j])
  if (substr(s[j],i,i)=="S") t[16]<-t[16]+10/nchar(s[j])
  if (substr(s[j],i,i)=="T") t[17]<-t[17]+10/nchar(s[j])
  if (substr(s[j],i,i)=="V") t[18]<-t[18]+10/nchar(s[j])
  if (substr(s[j],i,i)=="W") t[19]<-t[19]+10/nchar(s[j])
  if (substr(s[j],i,i)=="X") t[20]<-t[20]+10/nchar(s[j])
  if (substr(s[j],i,i)=="Y") t[21]<-t[21]+10/nchar(s[j])
}
}

# Here is the vector of counts of the time each amino acid
# appeared among the 10 most central nodes
# The online NAPS tool was done to create the networks
# and determine the eigenvalue centralities
# Determining the corresponding amino acids was done "by hand"
# using the PDB
y<-c(23,6,8,25,8,32,6,18,9,38,5,8,2,19,12,19,11,34,6,0,11)

plot(t,y,pch=19,xlab="Expected # central occurrences",ylab="Actual # central occurrences")
abline(a=0,b=1)

